sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CfB2QXPBsrcSVsOc0DgvgzKj9ixDcqmDVg74MaH1zAYa4K/Cm4xW2n+hrQTNtj9JlMW/s+lQuHc/Bvh+pf3bQhwny2njmELx+tgBjeJs4PUkAu2H9q4+WAVpMzRGmOjVP7FTHpqBqAqWXVCICC85lnT2/DnxR5dzUyIs3BIn77d54NgZlVxL+vOZBjA7Ap9ex1HHlrVtkIfNBXubq41AN82JeqpsP81F+LpaEVQo0BO4wN7lKA8rcAg4fnrEJc+zH4ZfuKoakdLuHXBCsdMTJFTcdcMOXaP5hAFpnnP09YVnsPsNKXUFBJ972DlvoDqxIe7OAQm32qJEhpdGy90cU7PbZJe1sLj+NwuBj7WZ4k6qDMVN+6kZ4VN7Pjha/FFrjTbemu6KiK8hneAgVqhLOvKyxUws8DrxlexGZkMKdMyqZdaNuTeXNHcSCTtSGA65k0oRs9A0oIJf6iUXqJgUEkRnoiR8JGGL+bT9Sj14YYm/CfdrrBiwYagW4+Blk05roF3mq+4ItTgtz8BBpVjeIJCWwsqAZdLnXE2RLS9++jHVJ7l4Y3fbuJR6/LJYJaoGOsV4MEUnIgb4WgHVX6BiBWKcXF/dIA1IY0r3Vv6yPWwOKxwnDMFA8BWOPg+smshvMLohzI2Z30q9JxgYCyyN5x7Bx0bYhnDmFYv1OhwOTQI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Thorny-Path-Volume-07_5536
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy